#!/bin/bash
# Setup script for creating certificates for Netgear switches
# This script creates a Let's Encrypt certificate with the standard SAN pattern
# and configures the deploy hook for automatic renewal.
#
# Usage: ./setup-switch-cert.sh <switch-name> <domain> <model> <ip> <password>
#
# Example:
#   ./setup-switch-cert.sh sw-netgear-gs728tpp welland.mithis.com GS728TPP 10.1.5.14 secretpass

set -e

if [ $# -lt 5 ]; then
    echo "Usage: $0 <switch-name> <domain> <model> <ip> <password>"
    echo ""
    echo "Arguments:"
    echo "  switch-name  Short name of the switch (e.g., sw-netgear-gs728tpp)"
    echo "  domain       Base domain (e.g., welland.mithis.com)"
    echo "  model        Switch model (GS728TPP, S3300, etc.)"
    echo "  ip           Switch IP address"
    echo "  password     Switch admin password"
    echo ""
    echo "This will create a certificate with the following SANs:"
    echo "  - <switch-name>.<domain>  (primary)"
    echo "  - ipv4.<switch-name>.<domain>"
    echo "  - ipv6.<switch-name>.<domain>"
    echo "  - manage.<switch-name>.<domain>"
    echo "  - ipv4.manage.<switch-name>.<domain>"
    echo "  - ipv6.manage.<switch-name>.<domain>"
    exit 1
fi

SWITCH_NAME="$1"
DOMAIN="$2"
MODEL="$3"
IP="$4"
PASSWORD="$5"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERT_NAME="${SWITCH_NAME}.${DOMAIN}"

# Build the list of SANs
# Primary SAN is <switch-name>.<domain>, others are secondary
SANS=(
    "${SWITCH_NAME}.${DOMAIN}"
    "ipv4.${SWITCH_NAME}.${DOMAIN}"
    "ipv6.${SWITCH_NAME}.${DOMAIN}"
    "manage.${SWITCH_NAME}.${DOMAIN}"
    "ipv4.manage.${SWITCH_NAME}.${DOMAIN}"
    "ipv6.manage.${SWITCH_NAME}.${DOMAIN}"
)

echo "=============================================="
echo "Setting up certificate for ${SWITCH_NAME}"
echo "=============================================="
echo ""
echo "Switch Details:"
echo "  Name:     ${SWITCH_NAME}"
echo "  Domain:   ${DOMAIN}"
echo "  Model:    ${MODEL}"
echo "  IP:       ${IP}"
echo ""
echo "Certificate SANs:"
for san in "${SANS[@]}"; do
    echo "  - ${san}"
done
echo ""

# Build certbot domain arguments
DOMAIN_ARGS=""
for san in "${SANS[@]}"; do
    DOMAIN_ARGS="${DOMAIN_ARGS} -d ${san}"
done

# Check if certificate already exists
if [ -d "/etc/letsencrypt/live/${CERT_NAME}" ]; then
    echo "Certificate already exists. Use --expand to add SANs or --force-renewal to replace."
    echo ""
    read -p "Expand existing certificate? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        CERTBOT_CMD="certbot certonly --expand --cert-name ${CERT_NAME}"
    else
        echo "Aborted."
        exit 1
    fi
else
    CERTBOT_CMD="certbot certonly --cert-name ${CERT_NAME}"
fi

# Create the deploy hook script
DEPLOY_HOOK="${SCRIPT_DIR}/deploy-hooks/deploy-${SWITCH_NAME}.sh"
echo "Creating deploy hook: ${DEPLOY_HOOK}"

# Determine cert file based on model
if [ "${MODEL}" = "GS728TPP" ]; then
    CERT_FILE='${RENEWED_LINEAGE}/cert.pem'
else
    CERT_FILE='${RENEWED_LINEAGE}/fullchain.pem'
fi

cat > "${DEPLOY_HOOK}" << HOOK_EOF
#!/bin/bash
# Deploy hook for ${SWITCH_NAME} (${MODEL}) certificate renewal
# Auto-generated by setup-switch-cert.sh

set -e

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
SWITCH_URL="http://${IP}"
SWITCH_MODEL="${MODEL}"
SWITCH_PASSWORD="${PASSWORD}"

CERT_FILE="${CERT_FILE}"
KEY_FILE='\${RENEWED_LINEAGE}/privkey.pem'

echo "Deploying certificate to \${SWITCH_MODEL} at \${SWITCH_URL}..."

python3 "\${SCRIPT_DIR}/netgear-updater.py" \\
    --switch-url "\${SWITCH_URL}" \\
    --model "\${SWITCH_MODEL}" \\
    --password "\${SWITCH_PASSWORD}" \\
    --cert-file "\${CERT_FILE}" \\
    --key-file "\${KEY_FILE}" \\
    --reboot

echo "Certificate deployed successfully to \${SWITCH_MODEL}"
HOOK_EOF

chmod +x "${DEPLOY_HOOK}"

echo ""
echo "Running certbot to obtain certificate..."
echo "Command: ${CERTBOT_CMD} ${DOMAIN_ARGS} --manual --preferred-challenges dns --manual-auth-hook /opt/certbot/bin/dnsmasq-hook.sh"
echo ""

# Run certbot
sudo ${CERTBOT_CMD} ${DOMAIN_ARGS} \
    --manual \
    --preferred-challenges dns \
    --manual-auth-hook /opt/certbot/bin/dnsmasq-hook.sh

# Add deploy hook to renewal config
RENEWAL_CONF="/etc/letsencrypt/renewal/${CERT_NAME}.conf"
if ! grep -q "renew_hook" "${RENEWAL_CONF}" 2>/dev/null; then
    echo ""
    echo "Adding deploy hook to renewal config..."
    sudo bash -c "echo 'renew_hook = ${DEPLOY_HOOK}' >> ${RENEWAL_CONF}"
fi

echo ""
echo "=============================================="
echo "Setup complete!"
echo "=============================================="
echo ""
echo "Certificate location: /etc/letsencrypt/live/${CERT_NAME}/"
echo "Deploy hook: ${DEPLOY_HOOK}"
echo "Renewal config: ${RENEWAL_CONF}"
echo ""
echo "To deploy the certificate now, run:"
echo "  sudo python3 ${SCRIPT_DIR}/netgear-updater.py \\"
echo "      --switch-url http://${IP} \\"
echo "      --model ${MODEL} \\"
echo "      --password '${PASSWORD}' \\"
echo "      --cert-file /etc/letsencrypt/live/${CERT_NAME}/cert.pem \\"
echo "      --key-file /etc/letsencrypt/live/${CERT_NAME}/privkey.pem \\"
echo "      --reboot"
